#!/usr/bin/env bash

# Service definition

# Bootstrap
. ./services.sh

# Friendly service name (mandatoty)
export SERVICE_NAME="Example Service"
# Command to run (mandatoty, array variable)
export SERVICE_CMD=("$(pwd)/test.sh" 'Hello world!')
# Working Directory (optional)
#SERVICE_WORK_DIR=
# On start (optional, array variable)
#SERVICE_ON_START=()
# On finish (optional, array variable)
#SERVICE_ON_FINISH=()

export PID_FILE_PATH="${SERVICE_NAME}.pid"
export LOG_FILE_PATH="${SERVICE_NAME}.log"

# Menu
serviceMenu "$1"

# vim: filetype=sh tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab